/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import javax.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.*;
/**
 *
 * @author admin
 */
public class Books extends javax.swing.JFrame {
   
    /**
     * Creates new form Librarian
     */
    public Books() {
        initComponents();
        tableModel = (DefaultTableModel) jTable1.getModel();
        loadBooks();
    }

    private DefaultTableModel tableModel;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        books = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        reserve = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        usbn = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        save_btn = new javax.swing.JButton();
        jSpinField1 = new com.toedter.components.JSpinField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        borrow_returns = new javax.swing.JLabel();
        users = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Library Management System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        books.setBackground(new java.awt.Color(255, 0, 0));
        books.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        books.setForeground(new java.awt.Color(255, 0, 0));
        books.setText("Manage Books");
        books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booksMouseClicked(evt);
            }
        });
        jPanel1.add(books, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        dashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        jPanel1.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        reserve.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reserve.setForeground(new java.awt.Color(255, 255, 255));
        reserve.setText("Reservations");
        reserve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reserveMouseClicked(evt);
            }
        });
        jPanel1.add(reserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 30, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1190, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USBN:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Author:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Book Title:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 51));
        jLabel11.setText("USBN:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Quantity:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Category:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));
        jPanel2.add(usbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 270, -1));
        jPanel2.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 270, -1));
        jPanel2.add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 270, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Romance", "Fiction", "Non-Fiction", "Arabic", "Computer ", "Biology", "Self-Help", "Drama", "Action", "Novel" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 270, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("ADD BOOKS");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        save_btn.setBackground(new java.awt.Color(0, 204, 0));
        save_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        save_btn.setText("ADD BOOKS");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jPanel2.add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 270, 30));
        jPanel2.add(jSpinField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 270, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 380, 420));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USBN", "Title", "Author", "Quantity", "Category"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 600, 420));

        borrow_returns.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        borrow_returns.setForeground(new java.awt.Color(255, 255, 255));
        borrow_returns.setText("Book Borrowing & Returns");
        borrow_returns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrow_returnsMouseClicked(evt);
            }
        });
        jPanel1.add(borrow_returns, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        users.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        users.setForeground(new java.awt.Color(255, 255, 255));
        users.setText("Manage Users");
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
        });
        jPanel1.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        update_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update_btn.setText("UPDATE");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 150, -1));

        delete_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete_btn.setText("DELETE");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 160, -1));

        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 570));

        setSize(new java.awt.Dimension(1205, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.setVisible(false);
      library_system_basc.Login object = new library_system_basc.Login();
      object.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
      String USBN = usbn.getText().trim();
    String Title = title.getText().trim();
    String Author = author.getText().trim();
    int qty = (Integer) jSpinField1.getValue();
    String Category = (String) jComboBox2.getSelectedItem();
    
    if (Title.isEmpty() || Author.isEmpty() || qty <= 0 || Category.equals("Select")){
    JOptionPane.showMessageDialog(this, "Please fill the right value and fields");
    return;
    }
    
    try(Connection conn = new library_system_basc.DBConnection().getConnection()){
        String addSQL = "INSERT INTO `books`(`USBN`, `Title`, `Author`, `Quantity`, `Category`, `Date_Added`) VALUES (?,?,?,?,?,NOW())";
        try(PreparedStatement ps = conn.prepareStatement(addSQL)){
            ps.setString(1, USBN);
            ps.setString(2, Title);
            ps.setString(3, Author);
            ps.setInt(4, qty);
            ps.setString(5, Category);
            
            int rows = ps.executeUpdate(); 
            
            if (rows > 0) {
                Object[] rowData = { USBN, Title, Author, qty, Category };
                tableModel.addRow(rowData);
                JOptionPane.showMessageDialog(this, "You Successfully Added " + USBN);
            }
        }
    } catch(SQLException e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_save_btnActionPerformed

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
       this.setVisible(false);
       Dashboard object = new Dashboard();
       object.setVisible(true);
    }//GEN-LAST:event_dashboardMouseClicked

    private void booksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksMouseClicked
       this.setVisible(false);
       Books object = new Books();
       object.setVisible(true);
    }//GEN-LAST:event_booksMouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        //Clear fields
        clear();
        
    }//GEN-LAST:event_clearActionPerformed
    public void clear(){
    jSpinField1.setValue(0);
        usbn.setText("");
        title.setText("");
        author.setText("");
        jComboBox2.setSelectedIndex(0);
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     int row = jTable1.getSelectedRow();
if (row != -1) {
    Object usbnObj = jTable1.getValueAt(row, 0);
    int USBN;
    if (usbnObj instanceof Integer) {
        USBN = (Integer) usbnObj;
    } else if (usbnObj instanceof String) {
        try {
            USBN = Integer.parseInt((String) usbnObj);
        } catch (NumberFormatException e) {
            return;
        }
    } else {
        return;
    }

    String Title = String.valueOf(jTable1.getValueAt(row, 1));
    String Author = String.valueOf(jTable1.getValueAt(row, 2));
    String qtyStr = String.valueOf(jTable1.getValueAt(row, 3));
    String Category = String.valueOf(jTable1.getValueAt(row, 4));

    // Set your fields
    usbn.setText(String.valueOf(USBN));
    title.setText(Title);
    author.setText(Author);
    jSpinField1.setValue(Integer.parseInt(qtyStr));
    jComboBox2.setSelectedItem(Category);
}
    }//GEN-LAST:event_jTable1MouseClicked

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
     int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        getToolkit().beep();
        JOptionPane.showMessageDialog(this, "Please select a book to update");
        return;
    }

    Object usbnObj = jTable1.getValueAt(selectedRow, 0);
    int originalUSBN;
    if (usbnObj instanceof Integer) {
        originalUSBN = (Integer) usbnObj;
    } else if (usbnObj instanceof String) {
        try {
            originalUSBN = Integer.parseInt((String) usbnObj);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid ISBN format");
            return;
        }
    } else {
        JOptionPane.showMessageDialog(this, "Invalid ISBN data");
        return;
    }

   
    int newUSBN;
    try {
        newUSBN = Integer.parseInt(usbn.getText().trim()); 
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid new USBN");
        return;
    }

    String Title = title.getText().trim();
    String Author = author.getText().trim();
    int Quantity = jSpinField1.getValue();
    String Category = (String) jComboBox2.getSelectedItem();

    if (Title.isEmpty() || Author.isEmpty() || Quantity == 0 || Category.equals("Select")) {
        JOptionPane.showMessageDialog(this, "Please fill all the fields correctly");
        return;
    }

    try (Connection conn = new library_system_basc.DBConnection().getConnection()) {
        String updateSQL = "UPDATE books SET USBN=?, Title=?, Author=?, Quantity=?, Category=? WHERE USBN=?";
        try (PreparedStatement psUpdate = conn.prepareStatement(updateSQL)) {
            psUpdate.setInt(1, newUSBN);       
            psUpdate.setString(2, Title);
            psUpdate.setString(3, Author);
            psUpdate.setInt(4, Quantity);
            psUpdate.setString(5, Category);
            psUpdate.setInt(6, originalUSBN);    

            int affectedRows = psUpdate.executeUpdate();

            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this, "Successfully updated the book with USBN " + originalUSBN);
                loadBooks(); 
                clear();     
            } else {
                JOptionPane.showMessageDialog(this, "Update failed. Please try again.");
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error updating books: " + e.getMessage());
    }
    }//GEN-LAST:event_update_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
       int selectedRow = jTable1.getSelectedRow();
       if(selectedRow == - 1){
       JOptionPane.showMessageDialog(this, "Please select a book to delete");
       return;
       }
       
    Object usbnObj = jTable1.getValueAt(selectedRow, 0);
    int USBN;
    if (usbnObj instanceof Integer) {
        USBN = (Integer) usbnObj;
    } else if (usbnObj instanceof String) {
        try {
            USBN = Integer.parseInt((String) usbnObj);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid ISBN format");
            return;
        }
    } else {
        JOptionPane.showMessageDialog(this, "Invalid ISBN data");
        return;
    }
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this book? ", "COnfirm Delete", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_NO_OPTION){
    return;
    }
    try(Connection conn = new library_system_basc.DBConnection().getConnection()){
    String DeleteSQL="DELETE FROM books WHERE usbn=?";
    try(PreparedStatement psDelete = conn.prepareStatement(DeleteSQL)){
    psDelete.setInt(1, USBN);
    
    int affectedRows = psDelete.executeUpdate();
    if(affectedRows > 0){
    JOptionPane.showMessageDialog(this, "You successfully deleted the " + USBN);
    loadBooks();
    clear();
    }
    else{
    JOptionPane.showMessageDialog(this, "Deletion failed. Book may not exist");
    }
    }
    }catch(SQLException ex){
    JOptionPane.showMessageDialog(this, "Error");
    }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
       this.setVisible(false);
       Users object = new Users();
       object.setVisible(true);
    }//GEN-LAST:event_usersMouseClicked

    private void borrow_returnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrow_returnsMouseClicked
        this.setVisible(false);
        Borrow_Return object = new Borrow_Return();
        object.setVisible(true);
    }//GEN-LAST:event_borrow_returnsMouseClicked

    private void reserveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveMouseClicked
       this.setVisible(false);
       Reservations object = new Reservations();
       object.setVisible(true);
    }//GEN-LAST:event_reserveMouseClicked
    
    
    
    public void loadBooks() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear existing data

    String sql = "SELECT USBN, Title, Author, Quantity, Category FROM books ORDER BY Title ASC";

    try (Connection conn = new library_system_basc.DBConnection().getConnection();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            String usbN = rs.getString("USBN");
            String title = rs.getString("Title");
            String author = rs.getString("Author");
            int quantity = rs.getInt("Quantity");
            String category = rs.getString("Category");

            Object[] rowData = { usbN, title, author, quantity, category };
            model.addRow(rowData);
        }

    } catch (SQLException e) {
        
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField author;
    private javax.swing.JLabel books;
    private javax.swing.JLabel borrow_returns;
    private javax.swing.JButton clear;
    private javax.swing.JLabel dashboard;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel reserve;
    private javax.swing.JButton save_btn;
    private javax.swing.JTextField title;
    private javax.swing.JButton update_btn;
    private javax.swing.JTextField usbn;
    private javax.swing.JLabel users;
    // End of variables declaration//GEN-END:variables
}
